baseurl = "https://prabhat496.github.io/shunyaweb/"
title = "Team Shunya"
theme = "dimension"
publishDir= "docs"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = "Our new website is under construction, please wait"
  logo = "fa-home"
  copyright = "teamshunya"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/IITB_TeamSHUNYA"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/teamshunya/"

[[params.social]]
  medium = "youtube"
  icon = "youtube"
  link = "https://www.youtube.com/user/TeamShunya"


[languages]
[languages.en]
languageName = "English"
weight = 1

# [languages.de]
# languageName = "Deutsch"
# weight = 2
# title = "Team Shunya"
# description = 'building'

